services:

    # Access control service
    ks.core.ac:
        class: Ks\CoreBundle\Services\AC
        arguments: ["@request_stack", "%ks.core.pwd_management%"]

    # Data Tables Report
    ks.core.dt_report:
        class: Ks\CoreBundle\Services\DtReport
        arguments: []

    # menu builder
    ks.core.menubuilder:
        class: Ks\CoreBundle\Services\KnpMenuBuilder
        arguments: ["@router", "@doctrine.orm.entity_manager"]

    # User Persist Service
    ks.core.user_model:
        class: Ks\CoreBundle\Services\UserPersist
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", "@ks.core.ac", "@security.password_encoder"]

    # Role Persist Service
    ks.core.role_model:
        class: Ks\CoreBundle\Services\RolePersist
        arguments: ["@doctrine.orm.entity_manager", "@form.factory"]

    # Menu Persist Service
    ks.core.menu_model:
        class: Ks\CoreBundle\Services\MenuPersist
        arguments: ["@doctrine.orm.entity_manager", "@form.factory"]

    # AC Persist Service
    ks.core.ac_model:
        class: Ks\CoreBundle\Services\AcPersist
        arguments: ["@doctrine.orm.entity_manager", "@form.factory"]

    # Parameter Model Service
    ks.core.parameter_model:
        class: Ks\CoreBundle\Services\ParameterModel
        arguments: ["@doctrine.orm.entity_manager", "@form.factory"]

    # User Create Form
    ks.core.form.type.user_create:
        class: Ks\CoreBundle\Form\Type\UserCreateType
        arguments: ["@ks.core.ac"]
        tags:
            - { name: form.type }

    # User Edit Form
    ks.core.form.type.user_edit:
        class: Ks\CoreBundle\Form\Type\UserEditType
        arguments: ["@ks.core.ac"]
        tags:
            - { name: form.type }

    # User Role Create Form
    ks.core.form.type.user_role_create:
        class: Ks\CoreBundle\Form\Type\UserRoleCreateType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    # ACL Create Form
    ks.core.form.type.acl_create:
        class: Ks\CoreBundle\Form\Type\AclCreateType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    # Menu Item Create Form
    ks.core.form.type.menu_item_create:
        class: Ks\CoreBundle\Form\Type\MenuItemCreateType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    # Menu Item Edit Form
    ks.core.form.type.menu_item_edit:
        class: Ks\CoreBundle\Form\Type\MenuItemEditType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    # User Checker
    ks.core.user_checker:
        class: Ks\CoreBundle\Security\UserChecker
        arguments: ["@ks.core.user_model", "%ks.core.login_security%", "%ks.core.login_security_threshold%"]

    # User Authentication
    ks.core.ks_authenticator:
        class:     Ks\CoreBundle\Security\KsAuthenticator
        arguments: ["@ks.core.user_checker", "@security.password_encoder", "%ks.core.pwd_management%", "@?ldap", "%ks.core.ldap_user_dn%"]