<?php

namespace Ks\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ACRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ACRepository extends EntityRepository
{
}
